name: nav
description: WebView NAV
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_webview_pro: ^3.0.1+4
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  dio: ^5.3.0
  open_filex: ^4.3.2
  connection_notifier: ^1.0.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.1


icons_launcher:
  image_path: "assets/icone.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/